### PR TITLE
Issue87 Clear and close revision display

### PR DESCRIPTION
**Pull request by sebbrudzinski**
The revision display window will now be closed when one of the following actions are performed:
 - A new file is opened from Dropbox
 - A connection with Dropbox is finished
 - The current file is uploaded as new file to Dropbox

### CODE REVIEW

**Comment by sebbrudzinski** [comment]
Geraldo, could you review and test this change?

**Comment by glandre** [comment]
Ok Sebastian, I will do it this week.
Bests,
Geraldo
Em 21/03/2016 16:26, "Sebastian Brudziński" <notifications@github.com>
escreveu:

**Comment by glandre** [comment]
Hi Sebastian,

The changes are OK in general. However, I tested disconnecting from Dropbox, but the Revision Display didn't close.
Repro steps:
- Connected with dropbox, with a dropbox file opened and also with the Revision Display opened:
- Disconnect from dropbox
- The connection is finished, the log presents the information, but the Revision Display stills opened.

**Comment by sebbrudzinski** [comment]
@glandre I've just tested this with those changes at it worked for me. Did you remember to pull the changes from this pull request first? (They are not merged to master yet) Please re-verify.

**Comment by glandre** [comment]
I tested it in its branch (dev/issue87). I'll merge it with the master to test.

**Comment by glandre** [comment]
@sebbrudzinski, maybe I did something wrong, because I've just fetch the branch from your repository (dev/issue87) and merged it to my master (which is ahead with changes from #73). Maybe we should first merge the branch related to issues #73.

Notice in the print screen attached that when I trigger "Disconnect from Dropbox" the Dropbox revision display doesn't close in my version.
disconnecting-from-dropbox

**Comment by sebbrudzinski** [comment]
@glandre I'll verify what happens when I first fetch your changes and then my changes, but I don't think it has got any impact on my changes... perhaps it does only work on Windows (I tested on Windows). Anyways, I'll be looking into it more to find the problem.

**Comment by sebbrudzinski** [comment]
@glandre I've noticed that there's a conflict and the changes in your pull request overwrite my changes (depending on how you resolve conflicts). Anyways, I'll hold my change until your change is closed and then resolve conflicts on my branch properly.

**Comment by sebbrudzinski** [comment]
@glandre I've merged the changes with master branch and resolved the conflicts. Everything should work OK now.

**Comment by glandre** [comment]
@sebbrudzinski, have this branch been merged with the master yet? Should we close it?

**Comment by sebbrudzinski** [comment]
No, it's awaiting aproval :> If you believe everything works fine now, feel free to merge.

**Comment by glandre** [comment]
OK! I'll check it out this weekend. =)

Geraldo B. Landre

2016-03-31 13:07 GMT-04:00 Sebastian Brudziński <notifications@github.com>:

**Comment by sebbrudzinski** [comment]
Hello @glandre. Do you think you will find enough time to check this pull request this week? It is the last remaining issue that I want to include in release 1.4, so once it's merged we will be able to start shipping Open LaTeX Studio 1.4

**Comment by glandre** [comment]
Hi @sebbrudzinski, I'll check it tomorrow without fail.

**Comment by glandre** [comment]
Great @sebbrudzinski ! Now it seems to work properly!

**Pull request merged**
