### PR TITLE
Issue #105 commit

### PR DESCRIPTION
**Pull request by Amitbhave**
Hi,

Issue fixed. Creating the pull request.

Thanks,
Amit

### CODE REVIEW

**Comment by klhes** [comment]
Hi Amit,

I'm a new contributor to Open LaTeX Studio, and I'm not a code reviewer, so take my comments with a grain of salt.  

I noticed a few things that might be helpful:

There are a lot of if statements in your fix, and I think it will be difficult for future contributors to quickly figure out what this code is doing.  I haven't spent much time thinking about how to fix this issue, but it seems like the logic would be something like (in pseudo-code):

```
if selected_page is the first page:
    disable previous_button
else:
    enable previous button

if selected_page is the last page:
    disable next_button
else:
    enable next_button
```

Writing methods like 'isFirstPage' and 'isLastPage' and calling those methods in the if statements might make things clearer. 

Also, you might consider changing the JButton variable names from jButton1 and jButton2 to something more descriptive (I know that you just used the existing names, but I think it's ok to change them).  

If you haven't changed variable names in the NetBeans design editor before, it's very simple. In the design tab, right-click on the item, select 'Change Variable Name', and enter the new name. NetBeans will change the name throughout the source code for you.

**Comment by Amitbhave** [comment]
Hi @klhes ,

Thanks for your valuable feedback. I actually don't know much about NetBeans editor as I have used Eclipse till now. I was actually wondering how to rename button names and all. Thanks for the info. Also I will refactor the code and make it more modular(by creating methods).

To clarify about the logic I used:
1)Changes in PDFPreviewRefresher.java:
Here in the constructor, I initialized the previous and next buttons  as-
      i)Disable previous button.
      ii)If total pages>1 : Enable next button
         Else Disable next button.

2)On click of Previous button:
     i)Enable next button
     ii)If selectedpage<2: Disable previous button

3)On click of Next button:
     i)Enable previous button
     ii)If selectedpage = totalpage: Disable next button.

Commiting changes again. Please have a look.

**Comment by aQaTL** [comment]
@Amitbhave I my opinion you should name your commit differently - instead of "Issue #xyz commit" describe what this particular commit changes in project. For Travisci errors - I also don't know exactly what way is correct. I am just making commit "Travisci error fix" or something like that. 

PS: I am also new contributor. I am not even a junior developer, so " take my comments with a grain of salt."

**Comment by klhes** [comment]
@Amitbhave Does your fix work when the user enters a page number in the page number text field?

Also, I see that you're passing jButton2 to the PDFDisplay.drawPreviewOnJPanel method. Currently, that method does one thing - it draws the PDF preview page on a JPanel.  We probably don't want that method to also handle changing a button.

**Comment by sebbrudzinski** [comment]
I agree with @klhes here. Currently the disable/enable buttons logic is scattered across two classes, that have their own responsibilities (drawing/refreshing preview). We should look for a cleaner solution than passing the buttons across whole PDF display logic.

**Pull request closed without merging**
