### PR TITLE
fixed an issue User is able to open a file that doesn't exist

### PR DESCRIPTION
**Pull request by Labelpm**
fixed an issue "User is able to open a file that doesn't exist"

### CODE REVIEW

**Comment by sebbrudzinski** [comment]
@LloydBG can you verify this change fixes the issue?

**Comment by LloydBG** [comment]
Hi Sebastian,

I have searched for a way on how to download pull request from github to
retest this issue but I can't find a correct solution. Can you help me on
this?

Thank you!
Lloyd Galang

**Comment by sebbrudzinski** [comment]
From the command line (either Linux terminal or Git Bash):
In the Open LaTeX Studio directory

    git checkout -b Labelpm-master master
    git pull git://github.com/Labelpm/Open-LaTeX-Studio.git master

After you are finished reviewing 

    git checkout master

**Comment by Labelpm** [comment]
Please check warning message

**Comment by LloydBG** [comment]
@Labelpm thanks for the update!

@sebbrudzinski 
Here is the screenshot of the warning message.

**Comment by sebbrudzinski** [comment]
@Labelpm - I checked the two commits fixing the "Open file" option and they seem to work as expected. The code looks good as well, so I'm ready to merge this in. However the third commit in your pull request (fix undo/redo) cannot be accepted in the current form, which blocks the whole pull request. Can you remove these changes so I can merge the fix to Open file? You are free to create another pull request later on. The general rule is one pull request per one issue :) Cheers!

**Comment by Labelpm** [comment]
Hi Sebastian, Added a commit that gives back an old functionality. 13.07.2015, 21:11, "Sebastian Brudziński" <notifications@github.com>:@Labelpm - I checked the two commits fixing the "Open file" option and they seem to work as expected. The code looks good as well, so I'm ready to merge this in. However the third commit in your pull request (fix undo/redo) cannot be accepted in the current form, which blocks the whole pull request. Can you remove these changes so I can merge the fix to Open file? You are free to create another pull request later on. The general rule is one pull request per one issue :) Cheers!—Reply to this email directly or view it on GitHub.

**Pull request merged**
