### PR TITLE
Feature implemented: Remember last path

### LINKED ISSUE #63: Remember last path
When a path is chosen one time (e.g., when saving a .tex file, or changing the LaTeX distribution directory) it could be remembered for the next time, so that the user saves time if he/she wants to save a new document in the directory previously used.

### PR DESCRIPTION
**Pull request by glandre**
When a path is choosen one time, it is remembered for the next time so that the user could save time if he/she wants to save a new document in the same directory.
I created a property in ApplicationSettings (latexstudio.editor.settings.ApplicationSettings) called "user.lastdir" (please feel free to suggest a better name if this is the case). This pull request closes #63 by implementing the feature on both getSelectedFile and getSelectedDirectory methods from latexstudio.editor.files.FileChooserService so

### CODE REVIEW

**Comment by sebbrudzinski** [comment]
This pull request contains both finished issue and some work in progress, so I cannot merge or even review it. Please create a pull request with finished change only.

**Comment by glandre** [comment]
Ok, I'm sorry about that, I'm gonna split it up.
Em 12/12/2015 19:50, "Sebastian Brudziński" <notifications@github.com>
escreveu:

**Comment by glandre** [comment]
Hi Sebastian, I took off the changes that are not related to this implementation. My version seems to be the same as the master now. Did you merged it?

**Comment by sebbrudzinski** [comment]
@glandre No, this has not been merged. From what I can see, there are no changes at all on your repository at the moment.

**Comment by glandre** [comment]
I think now I requested correctly.
Please let me know if everything is OK now.

Geraldo B. Landre

2015-12-13 17:46 GMT-03:00 Sebastian Brudziński <notifications@github.com>:

**Comment by sebbrudzinski** [comment]
@glandre Yes, it looks all right now. I'll try to test and review it today

**Pull request closed without merging**
