### PR TITLE
partially solving issue #59

### PR DESCRIPTION
**Pull request by GaboFDC**
This solves most of the errors, @sebbrudzinski please review the changes and tell me if you think this was the right way.

Also I'm not sure who to change pdflatex_exe variable name.

There are still all the "Utility classes should not have a public or default constructor." errors which I don't know how to fix. 

Regards,

### CODE REVIEW

**Comment by sebbrudzinski** [comment]
@GaboFDC - for all utility classes (static methods exclusively) make sure that they have no public constructors. In case utility class has got no constructors at all, Java will generate a default, public no-args constructor, therefore we have to override this by adding a private no-args constructor that does nothing.

**Comment by GaboFDC** [comment]
Nice, but by doing this, the checkstyle says that the class should be final. Is this ok?

**Comment by sebbrudzinski** [comment]
@GaboFDC Perfectly fine

**Comment by GaboFDC** [comment]
There are 4 errors. 
The pdflatex_exe from DropboxRevisionsTopComponent and v_overwriting from GeneratePDF variables name's should be changed.
The switch on FileChooserService doesn't have default clause.
And the last one from DropboxRevisionsTopComponent: "Variable 'canEdit' must be private and have accessor methods." but this is auto generated code.

I would appreciate if you guide how to proceed on this cases.

**Comment by sebbrudzinski** [comment]
@GaboFDC 1. I suppose the problem with these variable names is using the underscore character, which is not wanted as per java coding convention. Try to adjust the names so they are camelCase and see if that helps. You can also try to make them more meaningful in the process. 
2. Just add a default clause then; it may do nothing
3. We can leave that for now

**Comment by GaboFDC** [comment]
Done, now we just have 1 error, from DropboxRevisionsTopComponent: "Variable 'canEdit' must be private and have accessor methods." but this is auto generated code.

**Comment by sebbrudzinski** [comment]
After reviewing the code and a longer thought, I've removed the "AvoidInlineConditionals" from the checkstyle rules setup. I think the ternary operator "(condition) ? ifTrue : ifFalse" is known to many developers and it often helps reduce redundant code. Can we revert the changes with inline conditionals?

**Comment by GaboFDC** [comment]
Done, @sebbrudzinski please review.

**Pull request merged**
